'use strict';
const APP_VERSION='1.1-direct-study',STORAGE_KEY='adaptive_hoti0108_v1',$=id=>document.getElementById(id),E=HotiQuiz;
let bank=[],byId=new Map(),root={},state={},canSave=true,studyList=[],studyIndex=0,session=null,tick=null,deadline=0,started=0;
const titles={UF0080:'UF0080 · Organización del servicio',UF0081:'UF0081 · Gestión de la información',UF0082:'UF0082 · Atención al visitante'};
const VISUAL_SYSTEM=window.ADRIAN_VISUAL_SYSTEM||null;
const AVS_RANKS=VISUAL_SYSTEM?.ranks||[];
function applyVisualSystemTokens(){const r=document.documentElement;AVS_RANKS.forEach((x,i)=>{r.style.setProperty(`--rank-${i+1}`,x.color);r.style.setProperty(`--rank-${i+1}-surface`,x.surface||x.color);r.style.setProperty(`--rank-${i+1}-band`,x.band||x.color);r.style.setProperty(`--rank-${i+1}-text`,x.text||x.color);});}
function clamp(x,a=0,b=1){return Math.max(a,Math.min(b,x));}
function valueLevel(v){return Math.max(1,Math.min(15,Math.ceil(clamp(Number(v)||0)*15)));}
function valueColor(v){return (AVS_RANKS[valueLevel(v)-1]||{}).color||'#57965A';}
function valueTextColor(v){return (AVS_RANKS[valueLevel(v)-1]||{}).text||'#9EC29F';}
function scoreColor(v){return valueColor(clamp(v/15));}
function scoreTextColor(v){return valueTextColor(clamp(v/15));}
function avsLegendHtml(){return AVS_RANKS.map((x,i)=>`<div class="avs-legend-item"><i style="--swatch:${x.color}"></i><b>${i+1}</b></div>`).join('');}
function sessionScoreChart(rows){rows=(rows||[]).filter(x=>Number.isFinite(x.ts)&&Number.isFinite(x.equivalent15));if(rows.length<2)return '<div class="note">Sin datos suficientes.</div>';const mobile=innerWidth<=620,w=mobile?360:720,h=mobile?300:310,L=mobile?36:52,R=12,T=22,B=38,y=v=>T+((15-v)/15)*(h-T-B),first=rows[0].ts,last=rows[rows.length-1].ts,span=Math.max(1,last-first),x=(r,i)=>L+(last===first?i/(rows.length-1):(r.ts-first)/span)*(w-L-R);const bands=AVS_RANKS.map((c,i)=>`<rect x="${L}" y="${y(i+1)}" width="${w-L-R}" height="${Math.max(1,y(i)-y(i+1))}" fill="${c.band||c.color}" fill-opacity=".82"/>`).join('');const grid=[...Array(16).keys()].map(v=>`<line x1="${L}" y1="${y(v)}" x2="${w-R}" y2="${y(v)}" stroke="rgba(255,255,255,${v===0||v===15?'.35':'.12'})"/><text x="${L-7}" y="${y(v)+3}" text-anchor="end" fill="${v?scoreTextColor(v):'#b7c9bf'}" font-size="${mobile?8:10}" font-weight="850">${v}</text>`).join('');const pts=rows.map((r,i)=>({r,x:x(r,i),y:y(r.equivalent15),v:r.equivalent15}));const shadow=`<polyline points="${pts.map(q=>`${q.x.toFixed(1)},${q.y.toFixed(1)}`).join(' ')}" fill="none" stroke="#050806" stroke-opacity=".78" stroke-width="6" stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"/>`;const seg=pts.slice(1).map((q,i)=>`<line x1="${pts[i].x}" y1="${pts[i].y}" x2="${q.x}" y2="${q.y}" stroke="${scoreColor(q.v)}" stroke-width="3.2" stroke-linecap="round" vector-effect="non-scaling-stroke"/>`).join('');const dots=pts.map(q=>`<circle cx="${q.x}" cy="${q.y}" r="3" fill="${scoreColor(q.v)}" stroke="${scoreTextColor(q.v)}" stroke-width="1.5"><title>${q.r.correct}/${q.r.scored} correctas · ${q.v.toFixed(1)}/15</title></circle>`).join('');return `<svg class="score-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet"><rect x="${L}" y="${T}" width="${w-L-R}" height="${h-T-B}" rx="8" fill="#101815"/>${bands}${grid}${shadow}${seg}${dots}<text x="${L}" y="14" fill="#dfece5" font-size="${mobile?9:11}" font-weight="900">COLOR = AVS 1–15 · MÁS ALTO = MEJOR</text></svg><div class="chartmeta"><span>Última ${rows.at(-1).equivalent15.toFixed(1)}/15</span><span>${rows.length} rondas</span></div>`;}
function renderStatistics(){const rows=state.roundHistory||[],attempts=Object.values(state.attempts),recent=rows.slice(-10),scored=recent.reduce((n,r)=>n+r.scored,0),correct=recent.reduce((n,r)=>n+r.correct,0),acc=scored?correct/scored:null;$('statsRounds').textContent=rows.length;$('statsAccuracy').textContent=acc==null?'—':`${Math.round(acc*100)}%`;$('statsAccuracy').style.color=acc==null?'':valueTextColor(acc);$('statsAnswered').textContent=attempts.reduce((n,a)=>n+(a.count||0),0);$('scoreChart').innerHTML=sessionScoreChart(rows);$('avsLegend').innerHTML=avsLegendHtml();show('statistics');}
try{const raw=localStorage.getItem(STORAGE_KEY);root=raw?JSON.parse(raw):{};if(!root||typeof root!=='object'||Array.isArray(root))throw Error('shape');}catch{root={};canSave=false;}
state={version:1,attempts:{},studyPositions:{},roundHistory:[],...((root.studyGame&&typeof root.studyGame==='object')?root.studyGame:{})};
if(!state.attempts||typeof state.attempts!=='object')state.attempts={};if(!state.studyPositions||typeof state.studyPositions!=='object')state.studyPositions={};if(!Array.isArray(state.roundHistory))state.roundHistory=[];
function notice(){ $('storageNotice').hidden=false;$('storageNotice').textContent='Puedes seguir practicando, pero no se está guardando el progreso en este navegador.'; }
function save(){if(!canSave){notice();return;}try{localStorage.setItem(STORAGE_KEY,JSON.stringify({...root,studyGame:state}));}catch{canSave=false;notice();}}
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function show(id){for(const name of ['home','study','setup','game','results','statistics'])$(name).hidden=name!==id;window.scrollTo(0,0);}
function stopTimer(){if(tick)clearInterval(tick);tick=null;}
function pause(){stopTimer();if(session&&state.active===session&&session.index<session.ids.length&&session.answers.length===session.index&&session.limit&&deadline){session.remainingMs=Math.max(0,deadline-Date.now());state.active=session;save();}deadline=0;}
function pendingErrorCount(){return Object.values(state.attempts).filter(a=>a.lastKind==='wrong').length;}
function home(){pause();show('home');$('coverage').textContent=`${Object.values(state.attempts).filter(a=>a.count>0).length} / ${bank.length}`;const pending=pendingErrorCount();$('pendingErrors').textContent=pending;$('clearErrors').hidden=!pending;$('resumeGame').hidden=!state.active;}
function clearErrors(){for(const a of Object.values(state.attempts))if(a.lastKind==='wrong')a.lastKind='cleared';save();home();}
function assessment(q){return q.id.replace(/_Q\d+$/,'');}
function assessmentLabel(id){const tail=id.split('_').slice(1).join('_');return tail==='FINAL'?'Test final':tail;}
function metadata(q){return `${q.uf} · ${q.ud==='FINAL'?'Test final':q.ud} · Pregunta ${q.question_number} · Ficha ${String(q.global_index).padStart(3,'0')}`;}
function makeFilters(prefix){const container=$(prefix+'Filters');for(const kind of ['Unit','Assessment']){const wrap=node('div'),label=node('label',kind==='Unit'?'Unidad formativa':'Evaluación'),select=node('select');select.id=prefix+kind;label.htmlFor=select.id;wrap.append(label,select);container.append(wrap);}const unit=$(prefix+'Unit');unit.append(new Option('Todas las unidades','all'));Object.entries(titles).forEach(([value,text])=>unit.append(new Option(text,value)));unit.onchange=()=>{populateAssessments(prefix);filtersChanged(prefix);};$(prefix+'Assessment').onchange=()=>filtersChanged(prefix);populateAssessments(prefix);}
function populateAssessments(prefix){const select=$(prefix+'Assessment'),unit=$(prefix+'Unit').value;select.replaceChildren(new Option('Todas las evaluaciones','all'));[...new Set(bank.filter(q=>unit==='all'||q.uf===unit).map(assessment))].forEach(id=>select.append(new Option((unit==='all'?id.split('_')[0]+' · ':'')+assessmentLabel(id),id)));}
function selected(prefix){const unit=$(prefix+'Unit').value,a=$(prefix+'Assessment').value;return bank.filter(q=>(unit==='all'||q.uf===unit)&&(a==='all'||assessment(q)===a));}
function filtersChanged(prefix){if(prefix==='study')loadStudy();else poolInfo();}
function studyKey(){return $('studyUnit').value+'/'+$('studyAssessment').value;}
function renderPrompt(container,q,interactive=false){container.replaceChildren();container.dataset.questionId=q.id;container.append(node('p',metadata(q),'question-meta'));const h=node('h2',q.question,'question-text');h.id=interactive?'activeQuestion':'studyQuestion';container.append(h);const options=node('div',undefined,'options');options.setAttribute('role','group');options.setAttribute('aria-labelledby',h.id);for(const letter of ['a','b','c','d']){const o=node(interactive?'button':'div',undefined,'option');o.dataset.answer=letter;o.append(node('span',letter.toUpperCase(),'option-letter'),node('span',q.options[letter],'option-text'));if(interactive)o.onclick=()=>answer(letter);options.append(o);}container.append(options);}
function answerBody(q){const b=node('div',undefined,'answer-body');b.append(node('p',`Respuesta correcta · ${q.correct_answer.toUpperCase()}`,'answer-key'),node('p',q.options[q.correct_answer]));if(q.ambiguous)b.append(node('p',E.special(q),'special-note'));return b;}
function loadStudy(){state.studySelection={unit:$('studyUnit').value,assessment:$('studyAssessment').value};studyList=selected('study');const savedId=state.studyPositions[studyKey()];studyIndex=Math.max(0,studyList.findIndex(q=>q.id===savedId));const select=$('studyJump');select.replaceChildren();studyList.forEach((q,i)=>select.append(new Option(`${i+1}. ${q.uf} · ${q.ud} · Pregunta ${q.question_number}`,q.id)));renderStudy();}
function renderStudy(){const q=studyList[studyIndex];if(!q)return;state.studyPositions[studyKey()]=q.id;save();$('studyJump').value=q.id;$('studyPosition').textContent=`${studyIndex+1} de ${studyList.length} preguntas seleccionadas`;renderPrompt($('studyCard'),q);const details=node('details',undefined,'answer-details');details.append(node('summary','Ver respuesta'),answerBody(q));$('studyCard').append(details);$('studyPrev').disabled=studyIndex===0;$('studyNext').disabled=studyIndex===studyList.length-1;}
function moveStudy(delta){studyIndex+=delta;renderStudy();$('studyPosition').scrollIntoView({block:'start'});}
function pool(){return selected('game').filter(q=>!$('onlyErrors').checked||state.attempts[q.id]?.lastKind==='wrong');}
function poolInfo(){const n=pool().length;$('poolInfo').textContent=n?`${n} preguntas disponibles. Se usarán ${$('roundSize').value==='all'?n:Math.min(n,Number($('roundSize').value))}.`:'No hay fallos pendientes en esta selección. Desmarca el repaso o cambia de evaluación.';$('startGame').disabled=!n;}
function setup(){pause();show('setup');poolInfo();$('startGame').textContent=state.active?'Empezar una nueva ronda →':'Empezar ronda →';}
function start(ids=null){pause();let questions=ids?ids.map(id=>byId.get(id)).filter(Boolean):pool();if(!questions.length)return;const max=ids?questions.length:($('roundSize').value==='all'?questions.length:Number($('roundSize').value));session={ids:E.shuffle(questions).slice(0,max).map(q=>q.id),index:0,answers:[],limit:ids?0:Number($('timeLimit').value),streak:0,bestStreak:0,createdAt:Date.now()};state.active=session;save();show('game');renderGame();}
function resume(){session=state.active;if(!session)return;show('game');renderGame();}
function renderTimer(){const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('timer').textContent=`Tiempo restante: ${left} s`;$('timer').classList.toggle('urgent',left<=5);if(left<=0)answer(null);}
function renderGame(){stopTimer();deadline=0;const q=byId.get(session.ids[session.index]);if(!q){finish();return;}renderPrompt($('gameCard'),q,true);$('feedback').hidden=true;$('nextQuestion').hidden=true;$('roundPosition').textContent=`${session.index+1} / ${session.ids.length}`;$('roundStreak').textContent=`Racha ${session.streak}`;$('roundProgress').max=session.ids.length;$('roundProgress').value=session.answers.length;const previous=session.answers[session.index];$('timer').hidden=!session.limit||!!previous;
 if(previous){showFeedback(q,previous,false);return;}
 started=Date.now();if(session.limit){deadline=Date.now()+(session.remainingMs??session.limit*1000);delete session.remainingMs;renderTimer();if(session.answers.length===session.index)tick=setInterval(renderTimer,200);}
}
function answer(letter){if(!session||session.answers.length!==session.index)return;stopTimer();const q=byId.get(session.ids[session.index]),g=E.grade(q,letter);if(g.kind==='correct'){session.streak++;session.bestStreak=Math.max(session.bestStreak,session.streak);}else if(g.kind==='wrong')session.streak=0;
 const record={id:q.id,answer:letter,kind:g.kind,reason:g.reason||null,responseMs:Math.max(0,Date.now()-started),timestamp:Date.now()};session.answers.push(record);delete session.remainingMs;
 const old=state.attempts[q.id]||{count:0,correct:0,wrong:0,neutral:0};state.attempts[q.id]={...old,count:old.count+1,[g.kind]:(old[g.kind]||0)+1,lastKind:g.kind,lastAnswer:letter,lastMs:record.responseMs};state.active=session;save();showFeedback(q,record,true);
}
function showFeedback(q,record,scroll){const feedback=$('feedback');feedback.replaceChildren();feedback.className='feedback '+record.kind;const heading=record.kind==='correct'?'CORRECTO':record.kind==='neutral'?'PREGUNTA CON MATIZ':record.answer===null?'TIEMPO AGOTADO':'INCORRECTO';feedback.append(node('h2',heading));if(record.answer&&record.kind!=='correct')feedback.append(node('p',`Tu respuesta: ${record.answer.toUpperCase()} · ${q.options[record.answer]}`,'feedback-user-answer'));if(record.kind==='neutral')feedback.append(node('p','Sin penalización ni cambio de racha.'));const reveal=node('div',undefined,'feedback-correct-answer');reveal.append(node('small',`Respuesta correcta · ${q.correct_answer.toUpperCase()}`),node('strong',q.options[q.correct_answer]));feedback.append(reveal);if(q.ambiguous)feedback.append(node('p',E.special(q),'special-note'));for(const o of $('gameCard').querySelectorAll('.option')){o.disabled=true;if(o.dataset.answer===q.correct_answer){o.classList.add('correct');o.querySelector('.option-text').append(node('span','✓ Respuesta correcta','option-badge'));}else if(o.dataset.answer===record.answer){o.classList.add(record.kind==='neutral'?'neutral':'wrong');o.querySelector('.option-text').append(node('span',record.kind==='neutral'?'Tu respuesta · sin penalización':'Tu respuesta','option-badge'));}else{o.classList.add('dim');}}feedback.hidden=false;$('nextQuestion').hidden=false;$('nextQuestion').textContent=session.index===session.ids.length-1?'Ver resultado →':'Siguiente pregunta →';$('roundStreak').textContent=`Racha ${session.streak}`;$('roundProgress').value=session.answers.length;$('timer').hidden=true;if(scroll){feedback.focus({preventScroll:true});feedback.scrollIntoView({block:'center',behavior:'instant'});}}
function next(){if(session.answers.length<=session.index)return;session.index++;state.active=session;save();if(session.index===session.ids.length)finish();else{renderGame();$('game').scrollIntoView({block:'start'});}}
function finish(){stopTimer();deadline=0;const completed=session,totals=E.summarize(completed.answers),scored=totals.correct+totals.wrong;state.roundHistory.push({ts:Date.now(),correct:totals.correct,wrong:totals.wrong,neutral:totals.neutral,scored,total:completed.ids.length,equivalent15:scored?totals.correct/scored*15:0});state.roundHistory=state.roundHistory.slice(-500);state.lastResult=completed;state.active=null;session=null;save();renderResults(completed);}
function renderResults(s){show('results');const totals=E.summarize(s.answers),scored=totals.correct+totals.wrong;$('resultHeadline').textContent=scored?`${totals.correct} de ${scored} correctas`:'Sin preguntas puntuables';$('resultStats').replaceChildren();for(const [value,label] of [[totals.correct,'Aciertos'],[totals.wrong,'Fallos'],[s.bestStreak,'Mejor racha']]){const box=node('div');box.append(node('strong',String(value)),node('span',label));$('resultStats').append(box);}$('resultNote').textContent=totals.neutral?`${totals.neutral} pregunta(s) con matiz excluida(s) del cálculo.`:'';$('resultNote').hidden=!totals.neutral;const review=$('resultReview');review.replaceChildren();const mistakes=s.answers.filter(a=>a.kind==='wrong');for(const a of s.answers.filter(a=>a.kind!=='correct')){const q=byId.get(a.id),d=node('details',undefined,'review-item');d.append(node('summary',(a.kind==='neutral'?'Con matiz · ':'Repasar · ')+q.question),node('p',`Tu respuesta: ${a.answer?a.answer.toUpperCase()+' · '+q.options[a.answer]:'Sin respuesta'}`),answerBody(q));review.append(d);}$('retryMistakes').hidden=!mistakes.length;$('retryMistakes').onclick=()=>start(mistakes.map(a=>a.id));}
$('openStudy').onclick=()=>{pause();show('study');loadStudy();};$('clearErrors').onclick=clearErrors;$('openGame').onclick=setup;$('openStats').onclick=renderStatistics;$('statsStudy').onclick=()=>{show('study');loadStudy();};$('statsGame').onclick=setup;$('resumeGame').onclick=resume;document.querySelectorAll('.home-button').forEach(b=>b.onclick=home);$('pauseGame').onclick=home;$('studyJump').onchange=()=>{studyIndex=studyList.findIndex(q=>q.id===$('studyJump').value);renderStudy();};$('studyPrev').onclick=()=>moveStudy(-1);$('studyNext').onclick=()=>moveStudy(1);$('startGame').onclick=()=>start();$('onlyErrors').onchange=poolInfo;$('roundSize').onchange=poolInfo;$('nextQuestion').onclick=next;$('anotherRound').onclick=setup;
window.addEventListener('pagehide',pause);
async function boot(){try{applyVisualSystemTokens();const r=await fetch('./data/questions-mf1074.json');if(!r.ok)throw Error('bank');const data=await r.json();bank=data.questions;if(!bank.length||bank.some(q=>!q.id||!q.question||!q.options||!['a','b','c','d'].every(k=>typeof q.options[k]==='string')||!q.options[q.correct_answer]))throw Error('invalid bank');byId=new Map(bank.map(q=>[q.id,q]));
 if(state.active&&(!Array.isArray(state.active.ids)||!state.active.ids.length||state.active.ids.some(id=>!byId.has(id))||!Array.isArray(state.active.answers)||state.active.index>=state.active.ids.length)){state.active=null;}
 $('version').textContent='v'+APP_VERSION;$('questionCount').textContent=bank.length;makeFilters('study');makeFilters('game');if(state.studySelection){$('studyUnit').value=state.studySelection.unit;if(!$('studyUnit').value)$('studyUnit').value='all';populateAssessments('study');$('studyAssessment').value=state.studySelection.assessment;if(!$('studyAssessment').value)$('studyAssessment').value='all';}$('loadStatus').hidden=true;if(!canSave)notice();home();}catch(e){console.error(e);$('loadStatus').textContent='No se han podido cargar las preguntas. Comprueba la conexión y vuelve a abrir la aplicación.';}}
boot();
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').hidden=false;});$('installBtn').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').hidden=true;};window.addEventListener('appinstalled',()=>{$('installBtn').hidden=true;});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
